### compose file containing services to build images only

version: "3.7"

services:

  ### Building the dxpr/builder image
  dxpr-builder:
    image: dxpr/builder:$DXPR_BUILDER_MODE
    entrypoint: /bin/sh
    profiles: ["foo"]
    build:
      context: ./dxpr-builder
      args:
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
        DXPR_BUILDER_TAG: $DXPR_BUILDER_TAG
        PHP_TAG: $PHP_TAG
  
  ### Building the dxpr/qa-demo image
  qa-demo:
    image: dxpr/qa-demo
    container_name: "${PROJECT_NAME}_php"
    profiles: ["build"]
    build:
      context: .
      args:
        PHP_TAG: $PHP_TAG

  ### Building the dxpr/maven image
  maven:
    image: dxpr/maven
    profiles: ["build"]
    container_name: "${PROJECT_NAME}_maven"
    build:
      context: ./maven
      args: 
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
        DXPR_MAVEN_TAG: $DXPR_MAVEN_TAG
