version: "3.7"

services:
  
  ### Standalone chrome node
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210321
    container_name: "${PROJECT_NAME}_chrome"
    profiles: ["test"]
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  ### Selenium grid
  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210321
    container_name: "${PROJECT_NAME}_selenium_hub"
    profiles: ["test"]
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  ### Java selenium tests
  maven:
    image: dxpr/maven:$DXPR_MAVEN_TAG
    profiles: ["test"]
    container_name: "${PROJECT_NAME}_maven"
    depends_on:
    - chrome
