name: composer install tests

on:
  push:
  # to trigger manually with webhook
  # curl -X POST https://api.github.com/repos/:owner/:repo/dispatches \
  # -H 'Accept: application/vnd.github.everest-preview+json' \
  # -H 'Authorization: token TOKEN_VALUE_HERE' \
  # --data '{"event_type":"exec-composer-install","client_payload":{}}'
  repository_dispatch:
    types: [exec-composer-install]

env:
  DXPR_ACCESS_TOKEN: ${{ secrets.DXPR_ACCESS_TOKEN }}

jobs:

  composer-1:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: composer install -vvv
      run: |
        docker-compose run --rm composer-1


  composer-2:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: composer install -vvv
      run: |
        docker-compose run --rm composer-2
