
name: Run tests on qa-demo installation
on: [push]
env:
  DXPR_ACCESS_TOKEN: ${{ secrets.DXPR_ACCESS_TOKEN }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
  DXPR_ADMIN_PASSWORD: admin
  DXPR_DEMO: dxpr_qa_demo ### Available demos: [dxpr_basic_demo, dxpr_logistics_demo, dxpr_qa_demo]
  SITE_INSTALLATION_CONTAINER: /var/www/html:cached  ### This is where to mount the site installation volume inside the container

  ### DXPR_BUILDER SETUP
  DXPR_BUILDER_MODE: prod

  ### DXPR MAVEN SETUP
  DXPR_MAVEN_TAG: latest ### A valid maven image tag

  ### PROJECT SETTINGS
  PROJECT_NAME: my_drupal9_project
  PROJECT_BASE_URL: drupal.docker.localhost

  DB_NAME: drupal
  DB_USER: drupal
  DB_PASSWORD: drupal
  DB_ROOT_PASSWORD: password
  DB_HOST: mariadb
  DB_PORT: 3306
  DB_DRIVER: mysql
  MARIADB_TAG: 10.5-3.12.1

  DRUPAL_TAG: 9-4.28.0

  PHP_TAG: 7.4-dev-4.24.0

  NGINX_TAG: 1.19-5.13.1
  NGINX_VHOST_PRESET: drupal9
  NGINX_BACKEND_HOST: qa-demo
  NGINX_SERVER_ROOT: /var/www/html/docroot

  ATHENAPDF_TAG: 2.16.0
  DRUPAL_NODE_TAG: 1.0-2.0.0
  RSYSLOG_TAG: latest
  SELENIUM_CHROME_TAG: 3.141
  WEBGRIND_TAG: 1-1.21.1
  XHPROF_TAG: 2.7.1

jobs:
  qa-demo-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo $DOCKER_HUB_PASS | docker login docker.io -u $DOCKER_HUB_USER --password-stdin
      - run: ./scripts/qa-demo.github-action.sh